### ISSUE TITLE
Schedule Setting from CSV

### ISSUE THREAD

**Issue by dspecht** [Chronister/ChronalRobot#29]
https://forums.handmadehero.org/index.php/forum?view=topic&catid=5&id=65

handmadehero.org/broadcast.csv  is what Casey has done to put the schedule in one place for us and him. So at some point we should look at parsing the csv and updating the DB from it.

**Comment by kkartaltepe** [comment]
Along with this we should add a "Title" to the stream episode since casey Is providing it.

**Comment by dspecht** [comment]
Well Since no one ever said thing @Chronister maybe I should close this useless issue.
